declare module 'three' {
  const THREE: any;
  export default THREE;
  export const WebGLRenderer: any;
  export const Scene: any;
  export const PerspectiveCamera: any;
  export const BoxGeometry: any;
  export const MeshBasicMaterial: any;
  export const Mesh: any;
  export const Vector3: any;
  export const Color: any;
  export const AmbientLight: any;
  export const DirectionalLight: any;
  export const Clock: any;
  export const TextureLoader: any;
  export const Group: any;
  export const BufferGeometry: any;
  export const BufferAttribute: any;
  export const LineBasicMaterial: any;
  export const Line: any;
  export const SphereGeometry: any;
  export const MeshStandardMaterial: any;
  export const PointLight: any;
  export const CylinderGeometry: any;
  export const MeshPhongMaterial: any;
  export const PlaneGeometry: any;
  export const Raycaster: any;
  export const Euler: any;
  export const Quaternion: any;
  export const Matrix4: any;
  export const Math: any;
}